#!/usr/bin/env python3
"""Phase 8I - authors ``data/evaluation/phase8_queries.json`` (the page-level / end-to-end evaluation set) and verifies it against the corpus.

AUTHORSHIP DISCLOSURE: the queries below were written by the AI coding assistant (not a human domain expert, not generated by an LLM
at runtime) AFTER reading the seven ingested pages, so the answerable questions are paraphrases of facts that are on those pages
(deliberately not copied verbatim), and the "absent detail" questions were written to be about a page topic but NOT answered by the
page text (checked by a term search, not by a domain expert). Nothing was tuned afterwards: queries and pre-registered constants are
written before the first evaluation run and the evaluator refuses a query file whose ``preregistered`` block differs from the code.

Every answerable query carries ``evidence``: one or more VERBATIM quotes from the page text. This builder fails if a quote is not
found in the page text, so the retrieval hit definition (the chunk contains a quote) is strategy independent.

Query types: answerable | absent_detail | not_ingested | unresolved_identity | out_of_domain. Seven pages are ingested; a query
about the other 22 cards can only receive ``page_not_ingested`` (or ``unresolved_identity``), by design.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page_corpus as PC  # noqa: E402

ROOT = PC.ROOT
OUT = ROOT / "data" / "evaluation" / "phase8_queries.json"
OOD_SOURCE = ROOT / "data" / "evaluation" / "phase7F_ood_queries.json"

# (query, [evidence quotes])  -- answerable
ANSWERABLE = {
    "M2C-07": [
        ("Which transaction do I use to monitor meter reading results by different selection criteria?", ["You can use this transaction to monitor meter reading results based on different selection criteria."]),
        ("If I start from a device, what can I display?", ["If you start by entering devices, you can display meter reading orders or meter reading results."]),
        ("Which business function lets me display meter reading results when I begin with portions or reading units?", ["If the business function Utilities, Quantity Determination ( ISU_QD_1 ) is active, you can also display meter reading results."]),
        ("Which transaction triggers automatic follow-on processing for meter reading orders?", ["trigger automatic follow-on processing for selected meter reading orders"]),
        ("How can I see which meter reading documents were posted successfully after an IDoc upload?", ["display the successfully and unsuccessfully posted meter reading documents after uploading discrete meter reading data"]),
        ("How do I get an overview of the devices in a reading unit?", ["You can use this transaction to get an overview of the devices of a meter reading unit."]),
        ("What must be activated before I can run quantity determination from the result lists?", ["you have activated the business function Utilities, Quantity Determination ( ISU_QD_1 )"]),
        ("How do I jump to the detailed view of an object in the monitoring lists?", ["you can navigate to the detailed display of an object by choosing Edit > Select or by double clicking on the field in question"]),
        ("Why does the monitoring table mark some entries with an asterisk?", ["At first the system displays a summarized list grouped by date"]),
    ],
    "M2C-05": [
        ("What is the purpose of the device management component?", ["This component manages technical data, installations, meter readings, and the inspection of devices."]),
        ("A device in IS-U corresponds to which object in the standard system?", ["Name in IS-U: Device; From Component: Plant Maintenance (PM); Name in Standard System: Equipment"]),
        ("What does the device number map to outside IS-U?", ["Name in IS-U: Device Number; From Component: Logistics Basic Data (LO-MD); Name in Standard System: Serial Number"]),
        ("Where does a device number originate?", ["The device number is created in MM with the Goods Receipt function and transferred to the device."]),
        ("What makes a device unique and distinguishes it from other material with the same serial number?", ["The device is identified by a unique material and serial number combination"]),
        ("At what point are equipment records generated?", ["Equipment records are created automatically during goods receipt"]),
        ("Which purchasing component supplies requisitions and orders for device procurement?", ["Purchase Requisition and Purchase Order from Purchasing (MM-PUR)"]),
        ("Which component takes care of billing in the device flow?", ["Billing is then carried out with the Sales and Distribution (SD) component."]),
        ("Where can I read more about the advanced metering infrastructure?", ["you can find more information under Advanced Metering Infrastructure"]),
    ],
    "M2C-24": [
        ("Under what conditions should an installment plan be set up?", ["You create an installment plan when both of the following apply"]),
        ("Which transaction code starts the creation of an installment plan?", ["choose Account > Installment Plan > Create (transaction FPR1 )"]),
        ("Which indicator do I set to prioritize clearing of the original items when payments arrive?", ["you set the Clrg Priority indicator"]),
        ("Which fields does the system take over from the original item into the plan?", ["the system copies the company code, contract, business area, and business place from the original item"]),
        ("How can I avoid copying the company code and contract into the plan?", ["you can do this by defining event 3000 accordingly"]),
        ("Is it possible to have the first installment computed as a share of the plan total?", ["The system can calculate the first installment as a percentage of the total amount of the installment plan."]),
        ("What effect does the Distribute indicator have?", ["If you set the Distribute indicator, the interest and charges are distributed over all of the due dates."]),
        ("Where can the leftover amount of a plan be placed?", ["In the Remaining Amount field, specify whether this remaining amount is to be included in the first or last installment, or in a new installment."]),
        ("What can I edit in the installment plan proposal?", ["An Installment Plan Proposal appears, in which you can make the following changes"]),
        ("Which entries are mandatory when entering the plan parameters?", ["You must enter the installment interval and the interval type, as well as the installment plan category."]),
    ],
    "M2C-14": [
        ("What link does invoicing establish?", ["Invoicing creates the link to contract accounting and provides the basis for bill creation."]),
        ("What has to exist before invoicing can run?", ["Billing documents from the Contract Billing (IS-U-BI) component, or budget billing plans"]),
        ("What is the outcome of invoicing with bill creation?", ["Invoicing with Bill Creation results in a print document and a contract accounting document."]),
        ("Which document is needed to print a bill?", ["To print the bill, you require the print document."]),
        ("How do I tell customers about the number and due dates of their budget billings?", ["you use either the Partial Bill Creation function or the Budget Billing Request function"]),
        ("What do I use for bills that turn out to be wrong after they were updated in FI-CA?", ["you must process them using the Bill Reversal function"]),
        ("Which function reverses billing documents that were already invoiced?", ["you can use the Full Reversal function"]),
        ("When are postings made for a consumption bill that was outsorted?", ["Postings do not take place until the bill is released using the Outsorting function."]),
        ("What becomes of the bill once it has been created?", ["After the bill has been created, it is sent to the bill recipient."]),
    ],
    "M2C-17": [
        ("What does the contract account component enable?", ["This component enables you to create and manage contract account master data."]),
        ("May one business partner own several contract accounts?", ["You can assign more than one contract account to a given business partner."]),
        ("In utilities, which contracts are grouped in a single contract account?", ["one contract account contains all those contracts belonging to one business partner for which the same payment and dunning terms apply"]),
        ("Can an individual utility contract sit in more than one contract account?", ["each individual contract is assigned to one contract account only"]),
        ("How many business partners can a telecommunications contract account have?", ["a contract account can be assigned to one business partner only"]),
        ("Can a business transaction automatically block a contract account?", ["a return can result in a processing lock being set"]),
        ("Are modifications to contract account master data recorded?", ["The system logs changes to master data."]),
        ("How are contract accounts used for taxes in the public sector?", ["You set up the contract accounts of a business partner for the relevant taxes"]),
    ],
    "M2C-11": [
        ("What data does billing use to determine the evaluation basis?", ["Billing uses meter reading results or load profiles to determine the evaluation basis for schema execution."]),
        ("What does the system do if a price changes in the middle of a billing period?", ["a price change causes the system to divide the total period into subperiods"]),
        ("At which step are the rate calculations carried out?", ["All calculations required for rate creation are made during schema execution."]),
        ("Is it allowed for master data to change while a billing period is running?", ["All master and billing master data can change during a billing period."]),
        ("How is consumption handled when a billing period is split?", ["The system also divides the total consumption, which produces the corresponding partial amount."]),
        ("Which period categories can be handled by the billing procedures?", ["You can process all known period categories using different billing procedures."]),
    ],
    "M2C-02": [
        ("What does the move-in and move-out component let me do?", ["This component enables you to process a customer move-in or move-out."]),
        ("What happens to the customer's contract on a move-out?", ["In a move-out, you terminate the customer's contract."]),
        ("Which component produces welcome letters and move-out confirmations?", ["are created using the Print Workbench component"]),
        ("Which activities can the system start by itself during a move-in or move-out?", ["You can have the system trigger a number of activities automatically."]),
        ("Which component allows me to monitor and configure the workflow processes?", ["The SAP Business Workflow component (BC-BMT-WFM) enables you to monitor and configure the workflow processes."]),
        ("What can I do about the business partner and contract account when a customer moves in?", ["you can create a business partner and contract account for the customer, or select existing ones"]),
        ("What happens to an installation when a new customer moves in after a move-out?", ["If a new customer moves into the installation, the installation is allocated to this customer's contract."]),
        ("Can I adapt how the screen looks for move-in and move-out?", ["You can also configure the screen layout to suit your requirements."]),
    ],
}

# same topic as an ingested page, but the page text does not contain the answer. ``absent_terms`` must NOT occur in the page text.
ABSENT = [
    ("M2C-07", "Which authorization object controls access to the meter reading monitoring transaction?", ["authorization"]),
    ("M2C-07", "How long are meter reading results retained before they are archived?", ["archived", "retention"]),
    ("M2C-05", "How do I install a smart meter at a customer site step by step?", ["step by step", "smart meter"]),
    ("M2C-05", "What is the maximum number of devices that can be assigned to one installation?", ["maximum"]),
    ("M2C-24", "What interest rate applies to an installment plan?", ["interest rate"]),
    ("M2C-24", "How do I cancel an installment plan after it was saved?", ["cancel"]),
    ("M2C-14", "Can invoices be delivered to customers by e-mail?", ["e-mail", "email"]),
    ("M2C-14", "Which tax rate is applied during invoicing?", ["tax"]),
    ("M2C-17", "Which transaction creates a new contract account?", ["CAA1"]),
    ("M2C-11", "How do I start a billing run for a portion?", ["portion", "billing run"]),
    ("M2C-02", "How long does a move-out take to post in the system?", ["how long", "duration"]),
]

# about a card whose page is known (7C) but not ingested -> page_not_ingested
NOT_INGESTED = [
    ("M2C-26", "How are dunning notices created for overdue receivables?"),
    ("M2C-29", "How do I disconnect a utility installation for non-payment?"),
    ("M2C-27", "How do I submit open receivables to a collection agency?"),
    ("M2C-21", "What clearing types exist for incoming payments?"),
    ("M2C-25", "How can I display or change an existing installment plan afterwards?"),
    ("M2C-19", "How do I analyse incoming payments that have not been assigned?"),
]

# cards without an established page identity
UNRESOLVED = [
    ("M2C-18", "What is the contract account business object and what does it represent?"),
    ("M2C-18", "Which attributes does the contract account business object expose?"),
    ("M2C-13", "How is a budget billing plan set up for a customer?"),
    ("M2C-01", "How are business partner, premise and installation related in the utilities master data?"),
]

PREREGISTERED = {
    "declared_before_evaluation": True,
    "default_chunk_strategy": "B_heading_200",
    "router": "rank-1 of the card router, no similarity threshold (Phase 7F: min_cosine stays None)",
    "k_chunks": 5, "context_budget_tokens": 700, "max_context_chunks": 4,
    "ood_min_coverage": 0.25, "context_min_coverage": 0.5,
    "extractive_min_score": 0.34, "min_sentence_support": 0.6,
    "hit_definition": "a retrieved chunk whose text contains (whitespace-normalised) any evidence quote of the query",
    "answer_correct_definition": "status == answered AND at least one cited chunk contains an evidence quote AND the cited page is the gold page",
    "metrics_not_combined": ["routing", "identity", "retrieval", "generation", "citation"],
    "no_tuning_on_this_set": True,
}


def norm(t: str) -> str:
    return re.sub(r"\s+", " ", t.replace("\xa0", " ")).strip()


def main() -> int:
    recs = {r["source_ids"][0]: r for r in PC.load_records()}
    queries = []
    n = 0
    problems = []

    def add(**kw):
        nonlocal n
        n += 1
        queries.append({"id": f"P8-{n:03d}", **kw})

    for sid, items in ANSWERABLE.items():
        text = norm(recs[sid]["text"])
        for q, ev in items:
            for e in ev:
                if norm(e) not in text:
                    problems.append((sid, q, e))
            add(query=q, type="answerable", gold_source_id=sid, gold_doc_id=recs[sid]["doc_id"], evidence=ev, expected_status="answered")
    for sid, q, absent in ABSENT:
        text = norm(recs[sid]["text"]).lower()
        for a in absent:
            if a.lower() in text:
                problems.append((sid, q, f"absent term present: {a}"))
        add(query=q, type="absent_detail", gold_source_id=sid, gold_doc_id=recs[sid]["doc_id"], evidence=[], absent_terms=absent, expected_status="insufficient_context")
    for sid, q in NOT_INGESTED:
        add(query=q, type="not_ingested", gold_source_id=sid, gold_doc_id=None, evidence=[], expected_status="page_not_ingested")
    for sid, q in UNRESOLVED:
        add(query=q, type="unresolved_identity", gold_source_id=sid, gold_doc_id=None, evidence=[], expected_status="unresolved_identity")
    ood = [x for x in json.loads(OOD_SOURCE.read_text(encoding="utf-8"))["queries"] if x["label"] == "out_of_domain"]
    ood = sorted(ood, key=lambda x: x["id"])
    for x in ood[::7][:8]:
        add(query=x["query"], type="out_of_domain", gold_source_id=None, gold_doc_id=None, evidence=[], expected_status="out_of_domain", origin_id=x["id"])
    if problems:
        for p in problems:
            print("PROBLEM", p)
        return 1
    payload = {"schema_version": 1, "description": "Phase 8 page-level and end-to-end evaluation queries for the 7 ingested SAP Help pages",
               "authorship": {"authored_by": "AI coding assistant, after reading the ingested pages; not a human domain expert; no LLM generation at runtime",
                              "caveat": "answerable queries are paraphrases of page facts written with the page text in view; they are not blind. The set is small "
                                        "(per-page n of 6-10) and every metric derived from it is a point estimate with wide uncertainty.",
                              "written_before_evaluation": True, "labels_changed_after_retrieval": False,
                              "out_of_domain_origin": "every 7th out_of_domain query (sorted by id) of data/evaluation/phase7F_ood_queries.json, first 8"},
               "preregistered": PREREGISTERED,
               "counts": {t: sum(1 for q in queries if q["type"] == t) for t in ("answerable", "absent_detail", "not_ingested", "unresolved_identity", "out_of_domain")},
               "corpus_sha256": json.loads((PC.CORPUS_DIR / "manifest.json").read_text(encoding="utf-8"))["corpus_sha256"],
               "queries": queries}
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(queries)} queries {payload['counts']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
