"""PHASE 1-3 (read-only): local forensic search for SAP guide identifiers.

Searches every tracked file (as stored in git history, all commits), every untracked
file (labelled DERIVED: generated by this project's own tooling, not evidence), and the
internals of the 29 PDFs (all objects, decoded streams, annotations, metadata) for:
guide ids, page ids, card URLs, numeric deliverable ids, build numbers and SAP Help API
patterns. Nothing is inferred: a value is recorded only where it literally occurs.

    python scripts/forensic_search.py        ->  data/forensics/local_forensics.json
"""
from __future__ import annotations

import io
import json
import re
import subprocess
import sys
import zlib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.dont_write_bytecode = True
OUT = ROOT / "data" / "forensics" / "local_forensics.json"

HEX32 = re.compile(r"(?<![0-9a-fA-F])[0-9a-fA-F]{32}(?![0-9a-fA-F])")
KEYWORDS = ["deliverableInfo", "fullToc", "buildNo", "deliverable_id", "40374631", "http.svc", "pagecontent",
            "buildableMapLoio", "loio", "help.sap.com/http.svc", "help.sap.com/doc/", "help.sap.com/docs/",
            "help.sap.com/api", "help.sap.com/webapp", "/odata/", "deliverableMetadata", "landingPage"]
NUM_PATTERNS = {
    "deliverable_id= param": re.compile(r"deliverable_id=(\d+)"),
    "buildNo= param": re.compile(r"build_?[nN]o=(\d+)", re.I),
    "BUILD_NO / DELIVERABLE_ID constant": re.compile(r"\b(BUILD_NO|DELIVERABLE_ID)\s*=\s*[\"']?(\d+)"),
    "/docs/<product>/<numeric>/": re.compile(r"/docs/[A-Za-z0-9_\-]+/(\d{5,})/"),
    "/pagecontent or /doc/ with numeric": re.compile(r"/(?:doc|pagecontent)[^\s\"']*?(\d{6,})"),
}
ENDPOINT = re.compile(r"help\.sap\.com/(?:http\.svc|doc|docs|api|webapp|odata)[A-Za-z0-9_./\-]*(?:\?[^\s\"'<>]*)?")


def git(*a, binary=False):
    r = subprocess.run(["git", *a], cwd=ROOT, capture_output=True, check=True)
    return r.stdout if binary else r.stdout.decode("utf-8", "replace")


def pdf_views(data: bytes, name: str):
    """Yield (label, text) for raw bytes, every decoded stream/object, metadata and annotations."""
    yield "raw", data.decode("latin-1")
    try:
        from pypdf import PdfReader
        from pypdf.generic import IndirectObject
        rd = PdfReader(io.BytesIO(data))
        yield "metadata", json.dumps({k: str(v) for k, v in (rd.metadata or {}).items()})
        yield "xmp", str(getattr(rd, "xmp_metadata", None) and "xmp present")
        for i in range(1, (rd.trailer["/Size"] if "/Size" in rd.trailer else 0)):
            try:
                o = rd.get_object(IndirectObject(i, 0, rd))
            except Exception:
                continue
            if o is None:
                continue
            if hasattr(o, "get_data"):
                try:
                    yield f"obj{i}.stream", o.get_data().decode("latin-1")
                except Exception:
                    pass
            yield f"obj{i}", repr({k: v for k, v in o.items()}) if hasattr(o, "items") else repr(o)
        for n, p in enumerate(rd.pages):
            yield f"page{n}.text", p.extract_text() or ""
    except Exception as e:  # pragma: no cover
        yield "pdf_error", str(e)


def main():
    man = json.loads((ROOT / "data" / "topic_manifest.json").read_text(encoding="utf-8"))
    topics = man["topics"]
    guides = {}
    for t in topics:
        guides.setdefault(t["guide_id"], []).append(t["topic_id"])
    page_ids = {t["page_id"]: t["topic_id"] for t in topics}
    known_hex = set(guides) | set(page_ids)

    tracked = set(git("ls-files").split("\n")) - {""}
    all_files = [p for p in ROOT.rglob("*") if p.is_file() and ".git" not in p.relative_to(ROOT).parts
                 and "__pycache__" not in p.parts]
    sources = []   # (label, kind, bytes)
    # 1) history: every blob reachable from any ref (all commits), path-labelled
    commits = git("rev-list", "--all").split()
    seen_blobs = set()
    for c in commits:
        for line in git("ls-tree", "-r", c).splitlines():
            meta, path = line.split("\t", 1)
            blob = meta.split()[2]
            if blob in seen_blobs:
                continue
            seen_blobs.add(blob)
            sources.append((f"{path}@{c[:7]}", "history", git("cat-file", "blob", blob, binary=True)))
    # 2) untracked working-tree files: DERIVED (produced by this project's own tooling)
    for p in all_files:
        rel = str(p.relative_to(ROOT))
        if rel not in tracked and rel not in ("scripts/forensic_search.py", "scripts/inspect_pdf_cards.py",
                                              "data/forensics/local_forensics.json", "data/forensics/pdf_deep_inspection.json"):
            sources.append((rel, "derived_untracked", p.read_bytes()))

    res = {"commits_searched": commits, "files_searched": len(sources),
           "history_blobs": sum(s[1] == "history" for s in sources),
           "untracked_derived_files": sum(s[1] != "history" for s in sources)}
    hits_hex = defaultdict(lambda: defaultdict(list))        # hex -> kind -> [labels]
    kw = defaultdict(lambda: defaultdict(int))               # keyword -> label -> count
    nums = defaultdict(lambda: defaultdict(set))             # pattern -> value -> {labels}
    endpoints = defaultdict(set)
    other_hex = defaultdict(set)
    for label, kind, data in sources:
        views = pdf_views(data, label) if label.split("@")[0].lower().endswith(".pdf") else [("text", data.decode("utf-8", "replace"))]
        seen_here = set()
        for vname, text in views:
            for h in set(m.lower() for m in HEX32.findall(text)):
                if (h, vname) in seen_here:
                    continue
                seen_here.add((h, vname))
                if h in known_hex:
                    hits_hex[h][kind].append(f"{label}#{vname}")
                else:
                    other_hex[h].add(label)
            for k in KEYWORDS:
                c = text.count(k)
                if c:
                    kw[k][f"{label}#{vname}" if label.lower().endswith(".pdf") or "@" in label and label.split("@")[0].lower().endswith(".pdf") else label] += c
            for pname, rx in NUM_PATTERNS.items():
                for m in rx.finditer(text):
                    nums[pname][m.group(m.lastindex)].add(label)
            for m in ENDPOINT.finditer(text):
                e = m.group(0)
                e = HEX32.sub("<hex32>", e)
                e = re.sub(r"(?<=/)\d{5,}(?=/)", "<num>", e)
                endpoints[e].add(label)

    def labels(h, kind):
        # collapse pdf internals into file names
        return sorted({x.split("#")[0] for x in hits_hex.get(h, {}).get(kind, [])})

    table = []
    for gid, tids in guides.items():
        hist = labels(gid, "history")
        der = labels(gid, "derived_untracked")
        table.append({
            "guide_id": gid, "topic_ids": tids,
            "guide_id_occurrences_in_history": hist, "guide_id_occurrences_in_derived_files": der,
            "guide_id_in_non_PDF_history_files": [h for h in hist if not h.split("@")[0].lower().endswith(".pdf")],
        })
    res["guide_table"] = table
    res["page_id_occurrences"] = {
        pid: {"topic_id": tid, "history_files": labels(pid, "history"), "derived_files": labels(pid, "derived_untracked")}
        for pid, tid in sorted(page_ids.items(), key=lambda x: x[1])}
    res["keywords"] = {k: dict(sorted(v.items())) for k, v in sorted(kw.items())}
    res["numeric_patterns"] = {p: {v: sorted(l) for v, l in sorted(d.items())} for p, d in nums.items()}
    res["endpoint_patterns"] = {e: sorted(l) for e, l in sorted(endpoints.items())}
    res["other_32hex_ids_not_card_ids"] = {h: sorted(l) for h, l in sorted(other_hex.items())}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(res, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT))
    print(json.dumps({k: res[k] for k in ("commits_searched", "files_searched", "history_blobs", "untracked_derived_files")}))


if __name__ == "__main__":
    main()
